### ISSUE TITLE
perf_mddsPLS does not work correctly with one core

### ISSUE THREAD

**Issue by jonas-hag** [hlorenzo/ddsPLS#3]
`perf_mddsPLS` uses only the last `R` value if `NCORES = 1`. 
This code works as it should:
```
library(ddsPLS)
library(ggplot2)
data("liverToxicity")
X <- scale(liverToxicity$gene)
Y <- scale(liverToxicity$clinic)
res_cv_reg <- perf_mddsPLS(Xs = X,Y = Y,L0s=c(5,25,50,100,150,200),
                           R = c(1,3,5,7,9),NCORES = 2,mode = "reg",
                           plot_result = F)

df_errors <- cbind(res_cv_reg$RMSEP[,1:2],rowMeans(res_cv_reg$RMSEP[,-(1:2)]))
names(df_errors) <- c("R","L0","meanRMSEP")
ggplot(data=df_errors, aes(L0, meanRMSEP, color=factor(R))) + geom_line()
```
But if you use only one core, only the last `R` value is used:
```
res_cv_reg <- perf_mddsPLS(Xs = X,Y = Y,L0s=c(5,25,50,100,150,200),
                           R = c(1,3,5,7,9),NCORES = 1,mode = "reg",
                           plot_result = F)

df_errors <- cbind(res_cv_reg$RMSEP[,1:2],rowMeans(res_cv_reg$RMSEP[,-(1:2)]))
names(df_errors) <- c("R","L0","meanRMSEP")
ggplot(data=df_errors, aes(L0, meanRMSEP, color=factor(R))) + geom_line()
```

**Comment by hlorenzo** [comment]
Thank you jonas-hag, this is a very nice remark.
This must be fixed now.
You can use ``kfolds = 2`` as a parameter in ``perf_mddsPLS`` to test your version.
Thank you again!

**Comment by jonas-hag** [comment]
You committed into the branch Ridge_Deflation_ddsPLS and not master, can you update the master as well?

> 
> 
> You can use `kfolds = 2` as a parameter in `perf_mddsPLS` to test your version.

Do you mean in the CRAN version or your new updated version?

**Comment by hlorenzo** [comment]
It is pushed to the master. CRAN update takes a bit more time.
Thank you again

**Comment by jonas-hag** [comment]
Sorry to be so persistent, but it's still not in the master branch

**Comment by hlorenzo** [comment]
I think it must be now. Do not be sorryt, thank you for your help

**Comment by hlorenzo** [comment]
Do not hesitate to tell if all is fine for you now

**Comment by jonas-hag** [comment]
Sorry for the late reply; now it works also with one core, thanks for the bug fix!

**Comment by hlorenzo** [comment]
Nice! Thanks for the job done
